### ISSUE TITLE
 Search also based on the main category and cityName

### ISSUE THREAD

**Issue by Yang8547** [Luigi1000/SOEN-341_Project_Team-A#109]
add categories option in drop down list in search bar
add cityName option in in drop down list in search bar
#95

**Comment by daniakalomiris** [comment]
since the user can enter their province in their user profile, should there be an option in the drop list to also search by province?

**Comment by Yang8547** [comment]
Thank you Dania, I will try to add "all city" option in each province so that it can search in the whole province. for now, In the drop list, I will only keep 3 cities and 1 province(Quebec) that will be easy for demo. Do we need to add all provinces and all cities of Canada?

**Comment by daniakalomiris** [comment]
all provinces, but maybe keep the cities to a minimum like just a few major ones

**Comment by Yang8547** [comment]
issue fix
