### ISSUE TITLE
User profile page implement

### ISSUE THREAD

**Issue by Yang8547** [Luigi1000/SOEN-341_Project_Team-A#25]
1. create the user profile page which will have information about a user
2. that page can be accessed only once the user logged in
3. info contains the name, email, (address, contact number?) (need back-end query support)
4. this page can display all ads the current user has posted. (require pull info from database)  (need back-end query support)

**Comment by Anitarai** [comment]
I think we should also include " add user profile picture" feature. ( like Facebook)

**Comment by daniakalomiris** [comment]
@Anitarai We could consider including a profile picture. However, do we want the user's identity to be anonymous, only identified by their username?

**Comment by Anitarai** [comment]
@daniakal I think provide securely information is good idea but the thing is if we can add this feature that would be more valuable. It will give unique identification to each registered user with unique username... Its just the idea came into mind and I thought to discuss with you guys.

**Comment by daniakalomiris** [comment]
@Anitarai I will include it since it will compliment the listings once we restrict the type of products to be sold.

**Comment by Anitarai** [comment]
@daniakal thank you..
